---

- hosts:  ubuntu
  user:   ubuntu
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

- hosts:  centOS
  user:   garrettcottrell
  become: true
  tasks:

  - name: Install Apache and php packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
