---

- hosts:  ubuntu
  user:   ubuntu
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache 
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts:  centOS
  user:   garrettcottrell
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes

  - name: install httpd
    dnf:
      name: httpd
      state: latest

  - name: add php support for httpd
    dnf:
      name: php
      state: latest
